services:
  db:
    image: postgres:15-alpine
    container_name: trackit_db
    restart: always
    environment:
      POSTGRES_USER: trackit_user
      POSTGRES_PASSWORD: trackit_password
      POSTGRES_DB: trackit_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 🟢 اضافه شدن Redis
  redis:
    image: redis:7-alpine
    container_name: trackit_redis
    restart: always
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    container_name: trackit_ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trackit_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://trackit_user:trackit_password@db:5432/trackit_db
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_HOST=http://ollama:11434
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
      - ollama

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trackit_frontend
    restart: always
    command: npx vite --host 0.0.0.0 --port 3000
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
  ollama_data: