# app/seed.py
# Lancer depuis backend/ avec :  python -m app.seed

from sqlmodel import Session, select, SQLModel
from database import engine
from models import Application, Contact, ContactMethod
from datetime import datetime, timedelta


def seed():
    SQLModel.metadata.create_all(engine)

    with Session(engine) as session:
        # Évite les doublons si on relance le seed
        existing = session.exec(select(Application)).first()
        if existing:
            print("⚠️  La base contient déjà des données. Seed ignoré.")
            print("   (Vide database.db si tu veux re-seeder de zéro.)")
            return

        # ---- CANDIDATURES ----
        applications = [
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="accepted",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
                applied_at=datetime.now() - timedelta(weeks=2),
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
                applied_at=datetime.now() - timedelta(weeks=2),
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="technical_test",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="technical_test",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
                applied_at=datetime.now() - timedelta(weeks=2),
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="to_apply",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="to_apply",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="accepted",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="technical_test",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="technical_test",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="to_apply",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="to_apply",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="accepted",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
                applied_at=datetime.now() - timedelta(weeks=2),
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="technical_test",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="technical_test",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="to_apply",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="to_apply",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="accepted",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="interview",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="technical_test",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
                applied_at=datetime.now() - timedelta(weeks=2),
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="applied",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="technical_test",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="to_apply",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
            Application(
                company="Datadog",
                position="Alternant Software Engineer",
                url="https://careers.datadoghq.com/job-123",
                location="Paris",
                sector="Observabilité / Cloud",
                salary="1400€/mois",
                remote=True,
                status="rejected",
                notes="Entretien technique prévu la semaine prochaine.",
            ),
            Application(
                company="Doctolib",
                position="Alternant Développeur Full-Stack",
                url="https://careers.doctolib.com/job-456",
                location="Levallois-Perret",
                sector="HealthTech",
                salary="1300€/mois",
                remote=False,
                status="applied",
                notes="Candidature envoyée via le site.",
            ),
            Application(
                company="Qonto",
                position="Backend Engineer Apprentice",
                url="https://qonto.com/careers/job-789",
                location="Paris",
                sector="FinTech",
                salary="1500€/mois",
                remote=True,
                status="to_apply",
                notes="",
            ),
            Application(
                company="BlaBlaCar",
                position="Alternant Data Engineer",
                url="https://blablacar.com/jobs/job-321",
                location="Paris",
                sector="Mobilité",
                salary="1350€/mois",
                remote=True,
                status="rejected",
                notes="Refus après le premier entretien RH.",
            ),
            Application(
                company="Alan",
                position="Alternant Product Engineer",
                url="https://alan.com/jobs/job-654",
                location="Remote",
                sector="InsurTech",
                salary="1450€/mois",
                remote=True,
                status="rejected",
                notes="Test technique à rendre sous 5 jours.",
            ),
        ]
        session.add_all(applications)
        session.commit()
        for app in applications:
            session.refresh(app)

        # ---- CONTACTS (liés à une candidature) ----
        contacts = [
            Contact(
                name="Sophie Martin",
                notes="qdqsdsqdsqdsqdsqdsqdsqdsqdq",
                applications=[applications[0]],
            ),
            Contact(
                name="Thomas Dubois",
                notes="sqdsqdqsdsqd",
                applications=[applications[0]],
            ),
            Contact(
                name="Julie Bernard",
                applications=[applications[1], applications[2]],
            ),
            Contact(
                name="Marc Petit",
                applications=[applications[4], applications[3], applications[6]],
            ),
            # Contact libre (aucune candidature)
            Contact(name="Recruteur LinkedIn", applications=[]),
        ]
        session.add_all(contacts)
        session.commit()
        for c in contacts:
            session.refresh(c)

        # ---- MOYENS DE CONTACT ----
        methods = [
            ContactMethod(
                contact_id=contacts[0].id,
                type="email",
                value="sophie.martin@datadog.com",
            ),
            ContactMethod(
                contact_id=contacts[0].id,
                type="linkedin",
                value="linkedin.com/in/sophiemartin",
            ),
            ContactMethod(
                contact_id=contacts[1].id,
                type="email",
                value="thomas.dubois@datadog.com",
            ),
            ContactMethod(
                contact_id=contacts[2].id, type="phone", value="+33 6 12 34 56 78"
            ),
            ContactMethod(
                contact_id=contacts[3].id, type="email", value="marc.petit@alan.com"
            ),
            ContactMethod(
                contact_id=contacts[4].id,
                type="linkedin",
                value="linkedin.com/in/recruteur",
            ),
        ]
        session.add_all(methods)
        session.commit()

        print("✅ Seed terminé :")
        print(f"   {len(applications)} candidatures")
        print(f"   {len(contacts)} contacts")
        print(f"   {len(methods)} moyens de contact")


if __name__ == "__main__":
    seed()
